---
- name: Install Grafana as a Service
  hosts: all
  become: true

  tasks:
    - name: Update package repositories
      apt:
        update_cache: yes
      become: true

    - name: Install gnupg2, curl, and software-properties-common
      apt:
        name:
          - gnupg2
          - curl
          - software-properties-common
        state: present
      become: true

    - name: Import Grafana GPG key
      shell: curl -fsSL https://packages.grafana.com/gpg.key | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/grafana.gpg
      become: true

    - name: Add Grafana repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present
      become: true

    - name: Update package repositories again
      apt:
        update_cache: yes
      become: true

    - name: Install Grafana
      apt:
        name: grafana
        state: present
      become: true

    - name: Enable and start Grafana service
      systemd:
        name: grafana-server
        enabled: yes
        state: started
