---
- name: Install InfluxDB 2.7.0
  hosts: appserver
  become: true

  tasks:
    - name: Download InfluxDB package
      get_url:
        url: https://dl.influxdata.com/influxdb/releases/influxdb2-2.7.0-amd64.deb
        dest: /tmp/influxdb2-2.7.0-amd64.deb

    - name: Install InfluxDB package
      apt:
        deb: /tmp/influxdb2-2.7.0-amd64.deb

    - name: Start InfluxDB service
      service:
        name: influxdb
        state: started
