---
- name: Install InfluxDB
  hosts: appserver
  become: yes

  tasks:
    - name: Download InfluxDB package
      get_url:
        url: https://dl.influxdata.com/influxdb/releases/influxdb_1.8.10_amd64.deb
        dest: /home/chris/influxdb_1.8.10_amd64.deb

    - name: Install InfluxDB package
      apt:
        deb: /home/chris/influxdb_1.8.10_amd64.deb

    - name: Remove InfluxDB package file
      file:
        path: /home/chris/influxdb_1.8.10_amd64.deb
        state: absent      

    - name: Enable and start InfluxDB service
      systemd:
        name: influxdb
        state: started
        enabled: yes

    - name: Setup Influx Database
      shell: /home/chris/influx_setup.sh
      args:
        executable: /bin/bash
