---
- name: Install Services
  hosts: appserver
  gather_facts: false
  become: true

  tasks:
    - name: Install Grafana
      include_tasks: components/grafana.yml

    - name: Install InfluxDB 1.8
      include_tasks: components/influx_service.yml

    - name: Install Telegraf
      include_tasks: components/telegraf_service.yml

    - name: Configure InfluxDB & Telegraf
      shell: /home/chris/setup.sh
      args:
        executable: /bin/bash
