---
- name: Install Services
  hosts: appserver
  gather_facts: false
  become: true

  tasks:
    - name: Install Grafana
      include_tasks: components/grafana.yml

    - name: Install InfluxDB 1.8
      include_tasks: components/influx_service.yml

    - name: Install Telegraf
      include_tasks: components/telegraf_service.yml

    - name: Copy setup script to target
      copy:
        src: /home/chris/PMS18/Service_Playbooks/setup.sh
        dest: /home/chris/setup.sh
        mode: 0755  # Make the script executable

    - name: Execute setup script on target
      shell: /home/chris/setup.sh
      args:
        executable: /bin/bash
