---
- name: Configure LAMP Stack, Database, OwnCloud, Apache Config, and Apache Modules
  hosts: all
  become: true

  tasks:
    - name: Install Apache package
      apt:
        name: apache2
        state: present

    - name: Start and enable Apache service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Install MySQL package
      apt:
        name: mysql-server
        state: present

    - name: Start and enable MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Install PHP and required modules
      apt:
        name:
          - php
          - php-opcache
          - php-gd
          - php-curl
          - php-mysqlnd
          - php-intl
          - php-json
          - php-ldap
          - php-mbstring
          - php-mysqlnd
          - php-xml
          - php-zip
        state: present
        update_cache: yes

    - name: Restart Apache service
      service:
        name: apache2
        state: restarted

    - name: Create owncloud DB
      mysql_user:
        name: owncloud
        password: "dbp4ss"
        priv: "owncloud.*:ALL"
        host: localhost
        state: present
        login_user: root
        login_password: ""
      

    - name: Download OwnCloud archive
      get_url:
        url: "https://download.owncloud.org/community/owncloud-10.8.0.zip"
        dest: "/tmp/owncloud-10.8.0.zip"

    - name: Unzip OwnCloud archive
      unarchive:
        src: "/tmp/owncloud-10.8.0.zip"
        dest: "/var/www/html"
        remote_src: yes

    - name: Set ownership permissions
      file:
        path: "/var/www/html/owncloud"
        owner: www-data
        group: www-data
        recurse: yes

    - name: Remove existing owncloud.conf file
      file:
        path: "/etc/apache2/sites-available/owncloud.conf"
        state: absent

    - name: Create new owncloud.conf file
      copy:
        content: |
          <VirtualHost *:80>
            ServerAdmin admin@example.com
            DocumentRoot /var/www/html/owncloud
            ServerName example.com
            <Directory /var/www/html/owncloud>
              Options FollowSymlinks
              AllowOverride All
              Require all granted
            </Directory>

            ErrorLog ${APACHE_LOG_DIR}/example.com_error.log
            CustomLog ${APACHE_LOG_DIR}/your-domain.com_access.log combined
          </VirtualHost>
        dest: "/etc/apache2/sites-available/owncloud.conf"

    - name: Enable owncloud.conf
      command: a2ensite owncloud.conf

    - name: Enable Apache modules
      command: a2enmod rewrite mime unique_id

    - name: Restart Apache service
      service:
        name: apache2
        state: restarted
