---
- name: Install Docker, Telegraf & Containers
  hosts: testcontainers
  gather_facts: false
  become: true

  tasks:  
    - name: Install Docker
      include_tasks: components/docker.yml
      
    - name: Install Telegraf
      include_tasks: components/telegraf.yml
