---
- name: Install Docker, Telegraf & Containers
  hosts: testcontainers
  gather_facts: false
  become: true

  tasks:
  
    - name: Install Docker
      include_tasks: docker.yml
      
    - name: Install Telegraf
      include_tasks: telegraf.yml
