---
- name: Install Docker, Telegraf & Containers
  hosts: testcontainers
  gather_facts: false
  become: true

  tasks:  
    - name: Install Docker
      include_tasks: components/docker.yml
      
    - name: Telegraf
      include_tasks: components/telegraf.yml

    - name: Grafana Container
      include_tasks: components/grafana_container.yml

    - name: InfluxDB 1.8 Container
      include_tasks: components/influxdb_container.yml
    
    - name: Send Owncloud compose file to target
       copy:
         src: /path/to/my_compose.yml
         dest: target/dest/dir

     - name: Compose OwnCloud on target
       command: docker-compose -f target/dest/dir/my_compose.yml up -d




      
