  tasks:
    - name: Run InfluxDB Docker container
      command: docker run -d --name=influxdb --restart=always -p 8086:8086 -v influxvolume:/var/lib/influxdb influxdb:latest

    - name: Setup InfluxDB
      command: docker exec influxdb influx setup --username admin --password pms18project --org hua --bucket pms18 --force
