version: '3.9'

services:
  owncloud:
    image: owncloud/server:latest
    container_name: owncloud_srv
    ports:
      - "8080:8080"
    volumes:
      - ./data:/var/www/html
    environment:
      - OWNCLOUD_TRUSTED_DOMAINS=[TARGET_VM_IP]:8080
      - OWNCLOUD_ADMIN_USERNAME=[USERNAME]
      - OWNCLOUD_ADMIN_PASSWORD=[PASSWORD]

  db:
    image: mariadb:latest
    container_name: owncloud_db
    environment:
      - MYSQL_ROOT_PASSWORD=[PASSWORD]
      - MYSQL_DATABASE=[DB_NAME]
      - MYSQL_USER=[USERNAME]
      - MYSQL_PASSWORD=[PASSWORD]
    volumes:
      - ./db_data:/var/lib/mysql
